name: Run Gradle Build
on: [ push, pull_request ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Java
        with:
          java-version: '8'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: Artifacts
          path: dist/*.jar